version: "3.7"

services:

    rigs_api:
        container_name: rigs-api
        image: 77.37.200.24:5000/rigs-api
        build:
            context: .
            dockerfile: ./src/MNX.MonitoringCenter.RigsApi.Service/Dockerfile
            args:
                - nuget_server=http://77.37.200.24:8931/v3/index.json
        restart: unless-stopped
        ports:
             - "7101:8080"
        environment:
             - ApplicationUrl=http://77.37.200.24:7101
             - ServiceName=rigs-api
             - ConsulUri=http://77.37.200.24:8500

    monitoring_center_db:
        container_name: monitoring-center-db
        image: 77.37.200.24:5000/monitoring-center-db
        build:
            context: ./db
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - 6101:5432
        environment:
            - POSTGRES_DB=monitoring_center
            - POSTGRES_USER=MinuxDbAdmin
            - POSTGRES_PASSWORD=MinuxDbAdmin
