<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EasyNetQ" Version="7.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MNX.MonitoringCenter.Inventory.Contracts.Requests\MNX.MonitoringCenter.Inventory.Contracts.Requests.csproj" />
    <ProjectReference Include="..\MNX.MonitoringCenter.Inventory.Contracts\MNX.MonitoringCenter.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\MNX.MonitoringCenter.Inventory.UseCases\MNX.MonitoringCenter.Inventory.UseCases.csproj" />
  </ItemGroup>

</Project>
