insert into monitoring_center.algorithms(name) values
('Allium'),
('Argon2d-16000'),
('Argon2d-nim'),
('Argon2d4096'),
('Autolykos2'),
('Aurum'),
('AstroBWTv3'),
('BCD'),
('BeamHash III'),
('Blake (14r)'),
('Blake (2b)'),
('Blake (2s)'),
('Blake3 (Alephium)'),
('BMW512'),
('C11'),
('Conceal (CXX)'),
('Chukwa (Argon2id-Chuckwa)'),
('CNReverseWaltz'),
('Cortex'),
('CpuPower'),
('CryptoNightFemto'),
('CryptoNightPico'),
('CryptoNightArto'),
('CryptoNightConceal (Conceal)'),
('CryptoNightFast'),
('CryptoNightFastV2'),
('CryptoNightGPU'),
('CryptoNightHaven'),
('CryptoNightLiteV7'),
('CryptoNightR'),
('CryptoNightTalleo'),
('CryptoNightTurtle'),
('CryptoNightUPX2'),
('Cuckaroo29b'),
('Cuckaroo29S'),
('cuckAToo31'),
('cuckAToo32'),
('CuckooCycle (Cuckoo29)'),
('Curvehash'),
('DynexSolve'),
('Eaglesong'),
('Equihash'),
('Equihash(125,4)'),
('Equihash(144,5)'),
('Equihash(150,5)'),
('Equihash(192,7)'),
('Equihash(210,9)'),
('Equihash+Scrypt'),
('Etchash'),
('Ethash'),
('ETHash-B3'),
('FiroPoW'),
('FishHash'),
('GhostRider (Raptoreum)'),
('Groestl'),
('Gram'),
('HeavyHash'),
('HeavyHash-Pyrin (Pyrin, Pyrinhash)'),
('HMQ1725'),
('Blake3 (IronFish)'),
('KangarooTwelve'),
('KarlsenHash'),
('KawPoW'),
('Keccak'),
('KHeavyHash (Kaspa)'),
('Lyra2REv2 (WebChain)'),
('Lyra2z'),
('Memehash'),
('Memehash (ApepePow)'),
('Mike'),
('MinotaurX'),
('NeoScrypt'),
('NexaPoW'),
('NINJA (Argon2id-NINJA)'),
('Octopus'),
('Panthera'),
('PHI1612'),
('PHI2'),
('ProgPowSERO'),
('ProgPowVeil'),
('ProgPowZ'),
('PufferFish2BMB'),
('SHA-512-256D (Radiant)'),
('RandomARQ'),
('RandomEPIC'),
('RandomNEVO'),
('RandomSCASH'),
('RandomYADA'),
('RandomKEVA'),
('RandomGRAFT'),
('RandomHash2'),
('RandomSFX'),
('RandomTuske'),
('RandomWOW'),
('RandomX'),
('SHA-256csm'),
('SHA256DT'),
('SHA3d'),
('Skein'),
('Tribus'),
('Ton'),
('Ubqhash'),
('Verthash'),
('VerusHash'),
('vProgPoW'),
('X16R'),
('X16RT'),
('X16Rv2'),
('X16S'),
('X17'),
('X21S'),
('X25X'),
('Xevan'),
('Xelis (Xel)'),
('Xelis V2 (Xel)'),
('Yescrypt'),
('YescryptR16'),
('YescryptR32'),
('YescrptR8'),
('YesPoWer'),
('YesPoWerR16'),
('Zhash'),
('Ziliqa (ZIL)')
