insert into monitoring_center.algorithms(name) values
('Abelian'),
('Aergo'),
('Allium'),
('Argon2d-16000'),
('Argon2d-nim'),
('Argon2d-250'),
('Argon2d-4096'),
('Argon2d-Dyn (Dynamic)'),
('Autolykos2'),
('Aurum'),
('AstroBWTv3'),
('Astralhash'),
('BCD'),
('BFC'),
('Bitcore'),
('BeamHash III'),
('Balloon'),
('Blake (14r)'),
('Blake (2b)'),
('Blake (2s)'),
('Blake 256r8'),
('Blake3 (Alephium)'),
('Blakecoin'),
('BMW512'),
('C11'),
('Chukwa (Argon2id-Chuckwa)'),
('Chukwa2'),
('Circcash'),
('CNReverseWaltz'),
('Cortex'),
('CpuPower'),
('CryptoNight Femto'),
('CryptoNight Pico'),
('CryptoNight Alloy'),
('CryptoNight Arto'),
('CryptoNight ArtoCash'),
('CryptoNight B2N'),
('CryptoNight BBC'),
('CryptoNight Catalans'),
('CryptoNight Conceal (CCX)'),
('CryptoNight Dark'),
('CryptoNight Fast'),
('CryptoNight FastV2'),
('CryptoNight Fest'),
('CryptoNight GPU'),
('CryptoNight Haven'),
('CryptoNight IPBC'),
('CryptoNight Italo'),
('CryptoNight MarketCash'),
('CryptoNight Red'),
('CryptoNight ReverseWaltz'),
('CryptoNight Saver'),
('CryptoNight StelliteV4'),
('CryptoNight StelliteV8'),
('CryptoNight LiteV7'),
('CryptoNight R (CryptonightV4)'),
('CryptoNight Talleo'),
('CryptoNight Turtle'),
('CryptoNight UPX'),
('CryptoNight UPX2'),
('CryptoNight ZLS'),
('CryptoNight Zum-Lite'),
('CryptoNight Heavy'),
('CryptoNight HeavyX'),
('CryptoNight Lite'),
('CryptoNight V7'),
('CryptoNight V8'),
('CuckaRoo29b'),
('CuckaRoo29S'),
('CuckaRood29 (GRIN)'),
('CuckaRood29v'),
('CuckaRoom29'),
('CuckaRooz29'),
('CuckaToo31 (GRIN)'),
('CuckaToo32'),
('Cuckoo24'),
('CuckooBitCash'),
('CuckooCycle (Cuckoo29)'),
('Curvehash'),
('Darkcoin'),
('Decred (Blake3)'),
('Dedal'),
('DynexSolve'),
('Eaglesong'),
('Equihash'),
('Equihash (96,5)'),
('Equihash (125,4)'),
('Equihash BTG (144,5)'),
('Equihash (150,5)'),
('Equihash (150,5,3) (BeamHash II)'),
('Equihash Zero (192,7)'),
('Equihash (210,9)'),
('Equihash+Scrypt'),
('EtcHash'),
('Ethash (Ethereum)'),
('Ethash-B3'),
('EvrProgPow'),
('FiroPow'),
('FishHash'),
('GhostRider (Raptoreum)'),
('Groestl'),
('Handshake'),
('Gram'),
('HeavyHash'),
('Hex'),
('HeavyHash-Pyrin (Pyrin, Pyrinhash)'),
('Hmq1725'),
('HoneyComb'),
('HSR'),
('IronFish (Blake3)'),
('K12'),
('Kadena'),
('KangarooTwelve'),
('Karlsenhash'),
('KarlsenhashV2'),
('Kawpow'),
('Keccak'),
('Kaspa (KHeavyHash)'),
('LBK3'),
('LBRY'),
('Lyra2RE'),
('Lyra2REv2 (WebChain)'),
('Lyra2REv3'),
('Lyra2z'),
('Lyra2zz'),
('Lyra2z330'),
('M7M'),
('MegaBtx'),
('MegaMec'),
('Memehash'),
('Memehash (ApepePow)'),
('Meowpow'),
('Mike'),
('MinotaurX'),
('MTP'),
('Myrlad-Groestl'),
('NeoScrypt'),
('NeoScrypt Xaya'),
('NexaPow'),
('Nist5'),
('NINJA (Argon2id-NINJA)'),
('Octopus'),
('Pascal'),
('PawelHash'),
('Phi'),
('Phi2'),
('Polytimos'),
('PoUW'),
('Panthera'),
('ProgPow'),
('ProgPowSERO (SERO)'),
('ProgPowVeil'),
('ProgPowZ'),
('PyrinhashV2'),
('Quark'),
('Qubit'),
('PufferFish2BMB'),
('Radiant (SHA-512-256D)'),
('RainForest'),
('RainForestV2'),
('RandomArq'),
('RandomEpic'),
('RandomNEVO'),
('RandomSCASH'),
('RandomYADA'),
('RandomCash'),
('RandomKEVA'),
('RandomGRAFT'),
('RandomV'),
('RandomHash'),
('RandomHash2'),
('RandomSFX'),
('RandomTuske'),
('RandomWow'),
('RandomX'),
('RandomXL'),
('RX2'),
('Scrypt'),
('Scrypt Adaptive N'),
('Scrypt Jane'),
('ScryptN2'),
('SHA-256'),
('SHA-256 AsicBoost'),
('SHA-3 (Keccak)'),
('SHA-256csm'),
('SHA256DT'),
('SHA256Ton'),
('SHA3d'),
('Sia'),
('Skein'),
('Skein2'),
('Skunkhash'),
('Skydoge'),
('Solidity-SHA3'),
('Sonoa'),
('Tellor'),
('Tensority'),
('Timetravel'),
('Tribus'),
('Ton'),
('Ubqhash'),
('Verthash'),
('Verushash'),
('vProgPoW'),
('WhirlpoolX'),
('X11'),
('X11Evo'),
('X11Gost'),
('X12'),
('X13'),
('X14'),
('X15'),
('X16r'),
('X16rt'),
('X16rv2'),
('X16s'),
('X17'),
('X18'),
('X21s'),
('X25x'),
('Xevan'),
('XelisHash (Xel)'),
('XelisHashV2 (Xel)'),
('Yescrypt'),
('YescryptR8'),
('YescryptR16'),
('YescryptR32'),
('YescryptR8'),
('Yespower'),
('Yespower2B'),
('YespowerLitb'),
('YespowerLtncg'),
('YespowerR16'),
('YespowerSugar'),
('YespowerUrx'),
('Zhash (Equihash 144,5)'),
('Quai (ProgPow)'),
('Ziliqa (ZIL)');
