CREATE TABLE monitoring_center.rigs
(
    id uuid NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    owner_id uuid NOT NULL,
    name text NOT NULL,

    CONSTRAINT pk_rigs PRIMARY KEY (id)
);

CREATE INDEX ix_rigs_current_inventory_id
    ON monitoring_center.rigs USING btree

COMMENT ON TABLE monitoring_center.rigs IS 'Риги';
