CREATE TABLE monitoring_center.software_inventory
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    minux_version text,
    linux_version text,
    amd_gpu_driver_version text,
    nvidia_gpu_driver_version text,
    intel_gpu_driver_version text,
    open_cl_version text,
    cuda_version text,
    agent_version text,
    hardware_manager_version text,
    miners text,
    rig_inventory_id bigint NOT NULL,

    CONSTRAINT pk_software_inventory PRIMARY KEY (rig_inventory_id),

    CONSTRAINT fk_software_inventory_rig_inventory_rig_inventory_id FOREIGN KEY (rig_inventory_id)
        REFERENCES monitoring_center.rig_inventory (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE UNIQUE INDEX ix_software_inventory_inventory_id
    ON monitoring_center.software_inventory USING btree
    (rig_inventory_id ASC NULLS LAST);

COMMENT ON TABLE monitoring_center.software_inventory IS 'Инвентаризация программного обеспечения';
