<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MNX.MonitoringCenter.RigsApi.Contracts\MNX.MonitoringCenter.RigsApi.Contracts.csproj" />
    <ProjectReference Include="..\Management\MNX.MonitoringCenter.Management.Contracts\MNX.MonitoringCenter.Management.Contracts.csproj" />
    <ProjectReference Include="..\Management\MNX.MonitoringCenter.Management.UseCases\MNX.MonitoringCenter.Management.UseCases.csproj" />
    <ProjectReference Include="..\Traffic\MNX.MonitoringCenter.Traffic.Observers\MNX.MonitoringCenter.Traffic.Observers.csproj" />
  </ItemGroup>

</Project>
