// <auto-generated />
using System;
using MNX.MonitoringCenter.Management.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MNX.MonitoringCenter.Management.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Algorithm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Cryptocurrency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.HasIndex("FullName");

                    b.HasIndex("ShortName");

                    b.HasIndex("UserId");

                    b.ToTable("Cryptocurrencies");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Miner.Configs.MiningCoinConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid");

                    b.Property<string>("PoolPassword")
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("flight_sheet_target_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoolId");

                    b.HasIndex("WalletId");

                    b.HasIndex("flight_sheet_target_id");

                    b.ToTable("MiningCoinConfigs");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Miner.Miner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MiningMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupportedDevices")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Miners");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Miner.MinerAlgorithm", b =>
                {
                    b.Property<Guid>("MinerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlgorithmId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MinerId", "AlgorithmId");

                    b.ToTable("MinerAlgorithms");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.MiningDevice.MiningDeviceInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FlightSheetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FlightSheetIsConfirm")
                        .HasColumnType("boolean");

                    b.Property<string>("LifeCycleStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PresetId");

                    b.HasIndex("RigId");

                    b.ToTable("MiningDevices");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CryptocurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId");

                    b.HasIndex("UserId");

                    b.HasIndex("Domain", "Port");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CryptocurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    b.HasIndex("CryptocurrencyId");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Overclocking.GpuOverclocking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CoreClockLock")
                        .HasColumnType("integer");

                    b.Property<int>("CoreClockOffset")
                        .HasColumnType("integer");

                    b.Property<int>("CoreVoltage")
                        .HasColumnType("integer");

                    b.Property<int>("CoreVoltageOffset")
                        .HasColumnType("integer");

                    b.Property<int>("FanSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryClockLock")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryClockOffset")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryVoltage")
                        .HasColumnType("integer");

                    b.Property<int>("MemoryVoltageOffset")
                        .HasColumnType("integer");

                    b.Property<int>("PowerLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GpuOverclocking");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Overclocking.Preset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OverclockingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceName");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Presets");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.FlightSheetDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("UserId");

                    b.ToTable("FlightSheets");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.BaseFlightSheetTargetDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalArguments")
                        .HasColumnType("text");

                    b.Property<string>("ConfigFileContent")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FlightSheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MinerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlightSheetId");

                    b.HasIndex("MinerId");

                    b.ToTable("FlightSheetTargets");

                    b.HasDiscriminator<string>("DeviceType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.Overclocking.OverclockingDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CoreClockLock")
                        .HasColumnType("integer");

                    b.Property<int?>("CoreClockOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("CoreVoltage")
                        .HasColumnType("integer");

                    b.Property<int?>("CoreVoltageOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("FanSpeed")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryClockLock")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryClockOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryVoltage")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryVoltageOffset")
                        .HasColumnType("integer");

                    b.Property<int?>("PowerLimit")
                        .HasColumnType("integer");

                    b.Property<string>("TargetDeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Overclocking");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.CpuFlightSheetTargetDto", b =>
                {
                    b.HasBaseType("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.BaseFlightSheetTargetDto");

                    b.Property<int?>("HugePages")
                        .HasColumnType("integer");

                    b.Property<int?>("ThreadsCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("CPU");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.GpuFlightSheetTargetDto", b =>
                {
                    b.HasBaseType("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.BaseFlightSheetTargetDto");

                    b.HasDiscriminator().HasValue("GPU");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Cryptocurrency", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Algorithm", "Algorithm")
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Miner.Configs.MiningCoinConfig", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Pool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.BaseFlightSheetTargetDto", null)
                        .WithMany("CoinConfigs")
                        .HasForeignKey("flight_sheet_target_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Pool");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Miner.MinerAlgorithm", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Miner.Miner", null)
                        .WithMany("SupportedAlgorithms")
                        .HasForeignKey("MinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.MiningDevice.MiningDeviceInfo", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.Core.Overclocking.GpuOverclocking", null)
                        .WithMany()
                        .HasForeignKey("PresetId");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Pool", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Cryptocurrency", "Cryptocurrency")
                        .WithMany()
                        .HasForeignKey("CryptocurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cryptocurrency");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Wallet", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Cryptocurrency", "Cryptocurrency")
                        .WithMany()
                        .HasForeignKey("CryptocurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cryptocurrency");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.BaseFlightSheetTargetDto", b =>
                {
                    b.HasOne("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.FlightSheetDto", null)
                        .WithMany("Targets")
                        .HasForeignKey("FlightSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MNX.MonitoringCenter.Management.Core.Mining.Miner.Miner", "Miner")
                        .WithMany()
                        .HasForeignKey("MinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miner");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.Core.Mining.Miner.Miner", b =>
                {
                    b.Navigation("SupportedAlgorithms");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.FlightSheetDto", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("MNX.MonitoringCenter.Management.DataAccess.FlightSheet.Dto.Target.BaseFlightSheetTargetDto", b =>
                {
                    b.Navigation("CoinConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
