<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MNX.Application.Consul" Version="1.0.0" />
    <PackageReference Include="MNX.RigCommander.Contracts" Version="1.0.4" />
    <PackageReference Include="MNX.SecurityManagement.Authentication.Contracts" Version="1.2.3" />
    <PackageReference Include="MNX.SecurityManagement.Authentication.Integration" Version="1.2.3" />
    <PackageReference Include="NLog" Version="5.3.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.14" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory\MNX.MonitoringCenter.Inventory.Contracts.Requests\MNX.MonitoringCenter.Inventory.Contracts.Requests.csproj" />
    <ProjectReference Include="..\Inventory\MNX.MonitoringCenter.Inventory.Integration\MNX.MonitoringCenter.Inventory.Integration.csproj" />
    <ProjectReference Include="..\Management\MNX.MonitoringCenter.Management.Integration\MNX.MonitoringCenter.Management.Integration.csproj" />
    <ProjectReference Include="..\Management\MNX.MonitoringCenter.Management.UseCases\MNX.MonitoringCenter.Management.UseCases.csproj" />
    <ProjectReference Include="..\MNX.MonitoringCenter.RigsApi.UseCases\MNX.MonitoringCenter.RigsApi.UseCases.csproj" />
    <ProjectReference Include="..\Traffic\MNX.MonitoringCenter.Traffic.Integration\MNX.MonitoringCenter.Traffic.Integration.csproj" />
  </ItemGroup>

</Project>
